# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.2.1.dev57+ga88a5e6.d20230701"
__version_tuple__ = version_tuple = (0, 2, 1, "dev57", "ga88a5e6.d20230701")
