"""add rattlesnake tables and schema

Revision ID: 4299e43451be
Revises: cb8f1d4a92b4
Create Date: 2026-01-07 14:48:47.872685+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4299e43451be"
down_revision = "cb8f1d4a92b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "handled_messages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
        sa.Column("bot_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_type", sa.String(), nullable=False),
        sa.Column("reply_message_id", sa.BigInteger(), nullable=True),
        sa.Column("message_ts", postgresql.TIMESTAMP(timezone=True, precision=2), nullable=False),
        sa.Column(
            "handled_at",
            postgresql.TIMESTAMP(timezone=True, precision=2),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
        sa.UniqueConstraint("message_id"),
        sa.UniqueConstraint("reply_message_id"),
        schema="rattlesnake",
    )
    op.create_index(
        "idx_handled_messages_channel_message",
        "handled_messages",
        ["message_id", "channel_id"],
        unique=True,
        schema="rattlesnake",
    )
    op.create_index(
        op.f("ix_rattlesnake_handled_messages_handled_at"),
        "handled_messages",
        ["handled_at"],
        unique=False,
        schema="rattlesnake",
    )
    op.create_table(
        "message_decisions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "decided_at",
            postgresql.TIMESTAMP(timezone=True, precision=2),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
        sa.UniqueConstraint("message_id"),
        schema="rattlesnake",
    )
    op.create_index(
        "idx_message_decisions_channel_message",
        "message_decisions",
        ["message_id", "channel_id"],
        unique=True,
        schema="rattlesnake",
    )
    op.create_index(
        op.f("ix_rattlesnake_message_decisions_decided_at"),
        "message_decisions",
        ["decided_at"],
        unique=False,
        schema="rattlesnake",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rattlesnake_message_decisions_decided_at"),
        table_name="message_decisions",
        schema="rattlesnake",
    )
    op.drop_index(
        "idx_message_decisions_channel_message", table_name="message_decisions", schema="rattlesnake"
    )
    op.drop_table("message_decisions", schema="rattlesnake")
    op.drop_index(
        op.f("ix_rattlesnake_handled_messages_handled_at"),
        table_name="handled_messages",
        schema="rattlesnake",
    )
    op.drop_index("idx_handled_messages_channel_message", table_name="handled_messages", schema="rattlesnake")
    op.drop_table("handled_messages", schema="rattlesnake")
    # ### end Alembic commands ###
