name: pgvector build
run-name: pgvector (via ${{ github.event_name }})

on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

  pull_request:
    paths:
      - "docker/db/*"
      - ".github/workflows/build-push-pgvector.yml"
      - "!**.md"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: pgvector
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - pg_base: "15.3"
            pg_suffix: "bullseye"
            pg_vector: "v0.4.4"

    env:
      PGVECTOR_REF: ${{ matrix.pg_vector }}
      PG_BASE: ${{ matrix.pg_base }}
      PG_SUFFIX: ${{ matrix.pg_suffix }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.pg_base }},enable={{ is_default_branch }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Versioned Tags
        id: build-push
        uses: docker/bake-action@v3
        with:
          targets: ${{ env.IMAGE_NAME }}
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.force-push }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=min
